### PR TITLE
"Export without opening in Finder" plugin

### PR DESCRIPTION
**Pull request by rinatkhanov**
So I made a quick copy of original plugin for myself that doesn't open a new Finder window every time I update something in Sketch and run export. You need to install it as a separate plugin and use via menubar or `Cmd+Ctrl+Opt+P`.

Feel free to merge this PR (you'd also need to update README), though I suspect there's a better way to achieve this without code duplication.

### CODE REVIEW

**Comment by tarngerine** [comment]
Thanks for this pull. I'm aware of how annoying it is. I wonder if there's a way to capture an additional key press in the plugin and use that as a marker.

In general I've avoided multiple files in this plugin, as managing/installing a plugin with more than one file is a PITA for sketch (with sketchtoolbox, it's less of an issue, but I don't assume most people use it). I'll think more about how to make this happen without a dupe of files. Ideally we could've circumvented sandboxing and saved the file somewhere you can access later, but as it's in temp, I wanted to err on the side of safety so people can find their files. Thanks!

**Comment by tarngerine** [comment]
maybe i could use a time throttle to only auto open it once a day

**Comment by rinatkhanov** [comment]
Sure. Opening Finder window only once during the day wound seem random and confusing. I believe user should have a control when to open Finder window, because it's useful when you want to add new images to Origami (doesn't make sense to me to do it only once a day).

**Comment by tarngerine** [comment]
couple solutions i've been tinkering with:
- If you are running the plugin, check if you've made an export before. If you have, default to not opening the finder window. We already flash a message at the bottom, but add "Run plugin again within 3s to open the Finder window". If user runs plugin within 3s after, we open Finder window. 
- Using AppleScript to check current Finder paths opened - ran into sandboxing problem here.

I agree time based is confusing

**Comment by aentan** [comment]
A plugin can be a folder with multiple commands. Perhaps something like…
1. Export and reveal in finder
2. Export only

**Comment by tarngerine** [comment]
Yea now that the new plugin format supports a bundle I'll probably move to that format. I didn't want to have users manage two different plugins before

**Comment by tarngerine** [comment]
ill be doing this this week. lol 8 months later...

**Comment by tarngerine** [comment]
actually i forgot i already did this

**Pull request closed without merging**
